// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.3
//   protoc               v5.28.2
// source: src/proto/gateway-app.proto

/* eslint-disable */

export const protobufPackage = "gateway";
